In [1]:
import numpy as np
import cv2
import tracemalloc
#tracemalloc.start()
                # we will read the image directly as a grayscale image
img = cv2.imread('sample 2.png', cv2.IMREAD_GRAYSCALE) # gaussian filter is not used explicitly as it is already included in the canny function itself
drawn_image = cv2.imread("sample 2.png")

In [2]:
img = cv2.Canny(img,50,200)
#img = cv2.Sobel(img,cv2.CV_8U,2,2,7)
#img = cv2.dilate(img, None, iterations = 1)  # increases white portion by using a kernal such that atleast one element within should be white.
#img = cv2.erode(img, None, iterations = 1)   # reduces white portion by using a kernal such that all elements within should be white.

# I'm not using above functions for saving processing time in the later part of the code (for finding length). 

In [3]:
h,w = img.shape  #image dimensions in (no. of rows, no. of columns)
h,w

(339, 602)

In [5]:
lines = cv2.HoughLinesP(img,1,np.pi/180,150,maxLineGap = 40)  # HoughLines function gives an output of a 2d-array containing rho and theta values for the corresponding line equations which crossed the vote limit of 200.  
no_of_lines = len(lines) # this gives no. of edges lines identified and crossed vote limit by hough transformation.
print(lines,no_of_lines)            

[[[ 79 181 403 181]]

 [[ 79  81 402  81]]

 [[ 79 131 403 131]]

 [[ 79 176 402 176]]

 [[ 79 126 403 126]]

 [[ 79 231 403 231]]

 [[ 79  76 403  76]]

 [[ 81 226 401 226]]

 [[234 273 234  34]]

 [[335 271 335  34]]

 [[129 273 129  34]]

 [[330 273 330  34]]

 [[229 271 229  34]]

 [[134 273 134  34]]] 14


In [6]:
line_lengths = np.zeros(no_of_lines,dtype = int)  # to record the line lengths.
line_spacing = []
line_lengths  
#lines[2][0][0]
#line = lines[0]
#round(math.degrees(line[0][1]))  # just for calculation purposes

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
import math

for i in range(0,no_of_lines):
    y = lines[i][0][3] - lines[i][0][1]
    x = lines[i][0][2] - lines[i][0][0]
    line_lengths[i] = math.sqrt(y**2 + x**2)
    
line_lengths

array([324, 323, 324, 323, 324, 324, 324, 320, 239, 237, 239, 239, 237,
       239])

In [34]:
for i in range(0,no_of_lines-1):
    for j in range(i+1,no_of_lines):
        y = lines[i][0][3] - lines[i][0][1]
        x = lines[i][0][2] - lines[i][0][0]
        if (x != 0):
            a = round(np.degrees(np.arctan(y/x)))
        else:
            a = 90
        y1 = lines[j][0][3] - lines[j][0][1]
        x1 = lines[j][0][2] - lines[j][0][0]
        if (x != 0):
            b = round(np.degrees(np.arctan(y/x)))
        else:
            b = 90
        b = round(np.degrees(np.arctan(y1/x1)))
        if(a == b):
            midy = (lines[i][0][3] + lines[i][0][1])/2
            midx = (lines[i][0][2] + lines[i][0][0])/2
            midy1 = (lines[j][0][3] + lines[j][0][1])/2
            midx1 = (lines[j][0][2] + lines[j][0][0])/2
            string = "the lines "+str(i)+" and "+str(j)+" are parallel"
            dist = round(math.sqrt((midy1-midy)**2 + (midx1-midx)**2))
            line_spacing.append([string,dist])
        else:
            string = "the lines "+str(i)+" and "+str(j)+" are not parallel"
            dist = 0
            line_spacing.append([string,dist])
            
line_spacing

[['the lines 0 and 1 are parallel', 4]]

In [23]:
for i in range(len(lines)):
    cv2.line(drawn_image,(lines[i][0][0],lines[i][0][1]),(lines[i][0][2],lines[i][0][3]), color = (0,255,0), thickness = 2)

In [28]:
cv2.namedWindow('img',cv2.WINDOW_NORMAL)
cv2.imshow('img', img)

cv2.waitKey(0)

-1

In [4]:
cv2.imwrite('canny sample 2.png', img)

True

In [53]:
snapshot = tracemalloc.take_snapshot()
top_stats = snapshot.statistics('lineno')

print("[ Top 5 ]")
for stat in top_stats[:5]:
    print(stat)

[ Top 5 ]
<ipython-input-52-70f6d9c08e12>:3: size=393 KiB, count=2, average=196 KiB
<ipython-input-49-10b1e19b3402>:7: size=147 KiB, count=2, average=73.7 KiB
C:\Users\Sudhir\anaconda3\lib\json\decoder.py:353: size=33.5 KiB, count=381, average=90 B
C:\Users\Sudhir\anaconda3\lib\site-packages\IPython\core\compilerop.py:133: size=14.9 KiB, count=159, average=96 B
C:\Users\Sudhir\anaconda3\lib\site-packages\tornado\gen.py:191: size=12.9 KiB, count=28, average=472 B
