In [21]:
import numpy as np
import cv2
                # we will read the image directly as a grayscale image
img = cv2.imread('sample 4.png', cv2.IMREAD_GRAYSCALE) # gaussian filter is not used explicitly as it is already included in the canny function itself

In [22]:
img = cv2.Canny(img,50,200)
#img = cv2.dilate(img, None, iterations = 1)  # increases white portion by using a kernal such that atleast one element within should be white.
#img = cv2.erode(img, None, iterations = 1)   # reduces white portion by using a kernal such that all elements within should be white.

# I'm not using above functions for saving processing time in the later part of the code (for finding length). 

In [23]:
h,w = img.shape  #image dimensions
h,w

(198, 254)

In [24]:
lines = cv2.HoughLines(img,1,np.pi/180,150)  # HoughLines function gives an output of a 2d-array containing rho and theta values for the corresponding line equations which crossed the vote limit of 200.  
#no_of_lines = len(lines) # this gives no. of edges lines identified and crossed vote limit by hough transformation.
print(lines)            

[[[ 10  10 245 194]]

 [[  9   4 249 192]]]


In [34]:
line_lengths = np.zeros(no_of_lines,dtype = int)  # to record the line lengths.
line_spacing = []
line_lengths  
#lines[2][0][0]
line = lines[0]
round(math.degrees(line[0][1]))  # just for calculation purposes

128

In [64]:
for i in range(0,254):
    if(img[98][i]==255):
        print(i)
round(98*np.sin(128) + 130*np.cos(128))

122
123
128
129
130


-19.0

In [36]:
import math

for i in range(0,h):
    for j in range(0,w):
        if (img[i][j] == 255):
            for a in range(0,no_of_lines):
                temp = lines[a]
                rho = temp[0][0]; theta = temp[0][1]
                theta = round(math.degrees(theta))
                if (rho == ((j*(np.cos(theta)))+i*(np.sin(theta)))):
                    line_lengths[a] = line_lengths[a]+1

line_lengths   # the above loop is for calculating the no. of pixels on the edge. So, the line lengths are calculated in terms of pixel units. We can convert the calculated lengths into other units (say metres) by simply using pixel to metric ratio.

array([10, 68])

In [13]:
for i in range(0,no_of_lines-1):
    for j in range(i+1,no_of_lines):
        if (lines[i][0][1] == lines[j][0][1]):
            string = "distance between lines"+" "+str(i)+" "+" and "+" "+str(j)
            dist = abs(lines[i][0][0]-lines[j][0][0])
            line_spacing.append([string,dist])
        else:
            string = "lines "+str(i)+" and "+str(j)+" are not parallel."
            dist = 0
            line_spacing.append([string,dist])
            
line_spacing  # this list gives us the line spacing between every possible line combination.

[['distance between lines 0  and  1', 4.0]]

In [ ]:
cv2.namedWindow('img',cv2.WINDOW_NORMAL)
cv2.imshow('img', img)

cv2.waitKey(0)

In [11]:
cv2.imwrite('canny image3.jpg', img)

True